<SwapScreen>:

    GetInfoScreen:

    MainScreen:

    ClosedCases:

<GetInfoScreen>:
    name:"WelcomeScreen"

    BoxLayout:
        orientation:"vertical"
        padding:40

        MDLabel:
            text:"Covid-19 Updates"
            halign:"center"
            theme_text_color: "Custom"
            text_color: 1,1,1,1
            font_style:"H4"

        MDLabel:
            text:"By revibe"
            halign:"right"
            theme_text_color: "Custom"
            text_color: 1,1,1,1
            font_style:"H4"
        
        MDFillRoundFlatButton:
            text:"Get Latest Info"
            text_color: 1,1,1,1
            pos_hint:{"center_x":.5,"center_y":.5}
            font_size:25
            on_release:
                root.prompt()

<MainScreen>:
    name:"MainScreen"
    ti:ti
    ac:ac
    cc:cc
    covid:covid
    BoxLayout:
        orientation:"vertical"
        
        MDToolbar:
            title:"Covid-19 Statistics"
            left_action_items: [["menu", lambda x: root.covid.set_state("open")]]
            right_action_items: [["close", lambda x: root.askif()]]
            elevation: 10
            specific_text_color: 1,1,1,1

        MDLabel:
            text:"All Cases"
            halign:"center"
            theme_text_color: "Custom"
            text_color: 1,1,1,1
            font_style:"H4"

        BoxLayout:
            orientation:"horizontal"
            padding:10

            MDLabel:
                text:"Total Infected"
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"


            MDLabel:
                id:ti
                text:""
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

        BoxLayout:
            orientation:"horizontal"
            padding:10

            MDLabel:
                text:"Active Cases"
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"


            MDLabel:
                id:ac
                text:""
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

        BoxLayout:
            orientation:"horizontal"
            padding:10

            MDLabel:
                text:"Closed Cases"
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"


            MDLabel:
                id:cc
                text:""
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

    MDNavigationDrawer:
        id: covid

        ContentNavigationDrawer:

            ScrollView:

                MDList:

                    OneLineListItem:
                        text: "All Cases"
                        on_press:
                            root.covid.set_state("close")
                            root.change_Screen_all()

                    OneLineListItem:
                        text: "Closed Cases"
                        on_press:
                            root.covid.set_state("close")
                            root.change_Screen_Closed()
                            


<ClosedCases>:
    name:"ClosedCases"
    covid:covid
    trn:trn
    tdn:tdn
    tcc:tcc
    dr:dr
    rr:rr
    BoxLayout:
        orientation:"vertical"
        
        MDToolbar:
            title:"Covid-19 Statistics"
            left_action_items: [["menu", lambda x: root.covid.set_state("open")]]
            right_action_items: [["close", lambda x: root.askif()]]
            elevation: 10
            specific_text_color: 1,1,1,1

        MDLabel:
            text:"Closed Cases"
            halign:"center"
            theme_text_color: "Custom"
            text_color: 1,1,1,1
            font_style:"H4"

        BoxLayout:
            orientation:"horizontal"
            padding:10

            MDLabel:
                text:"Total Closed"
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

            MDLabel:
                id:tcc
                text:""
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

        BoxLayout:
            orientation:"horizontal"
            padding:10

            MDLabel:
                text:"Recovered"
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

            MDLabel:
                id:trn
                text:""
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

        BoxLayout:
            orientation:"horizontal"
            padding:10

            MDLabel:
                text:"Died"
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

            MDLabel:
                id:tdn
                text:""
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

        BoxLayout:
            orientation:"horizontal"
            padding:10

            MDLabel:
                text:"Death Ratio"
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

            MDLabel:
                text:"Recovery Ratio"
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

        BoxLayout:
            orientation:"horizontal"
            padding:10

            MDLabel:
                id:dr
                text:""
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"

            MDLabel:
                id:rr
                text:""
                halign:"center"
                theme_text_color: "Custom"
                text_color: 1,1,1,1
                font_style:"H4"



    MDNavigationDrawer:
        id: covid

        ContentNavigationDrawer:

            ScrollView:

                MDList:

                    OneLineListItem:
                        text: "All Cases"
                        on_press:
                            root.covid.set_state("close")
                            root.change_Screen_all()

                    OneLineListItem:
                        text: "Closed Cases"
                        on_press:
                            root.covid.set_state("close")
                            root.change_Screen_Closed()